### ISSUE TITLE
Disabled dates not disabled for dates greater than 10 october

### ISSUE THREAD

**Issue by rakshak4** [maurovieirareis/hello-week#43]
Hello

I am having an issue with disabled dates. I pass in the following dates in the 'disableDates' parameter:
![image](https://user-images.githubusercontent.com/17859129/81278763-29784300-9067-11ea-8b7a-c7216b0712ce.png)
However, dates after 2020-10-10 are not disabled. 
![image](https://user-images.githubusercontent.com/17859129/81278883-5b89a500-9067-11ea-8177-cc8d0c5bc236.png)

Im guessing, either the date format is not good or it is a bug.

Any advise on the issue would help

**Comment by mauroreisvieira** [comment]
Hi @rakshak4.

You disabled this days with what approach?

**1. Disabled days one by one:**
```js
new HelloWeek({
    disableDates: ["2020-10-02", "2020-10-28", "2020-10-29"]
});
``` 

**2. Disabled interval of days:**
```js
new HelloWeek({
    disableDates: [["2020-09-02", "2020-10-29"]]
});
```

If it's the first approach, can provide me the array of days to test and the version of HelloWeek that you are using ?

**Comment by rakshak4** [comment]
Im using method 1: one by one

Calender parameters (JSON):
[calParams.txt](https://github.com/mauroreisvieira/hello-week/files/4593314/calParams.txt)

version im using: 2.10.3

**Comment by mauroreisvieira** [comment]
@rakshak4 the issue is related with month format. 

Since you define the format date `yyyy-MM-dd` you should use `2020-06-10` on your array of dates.

If you want to use the format `2020-6-10` you should change the format date to `yyyy-mm-dd`.

**Solution: 1 -  Keep the `disableDates` as you have and change the `format` settings to:**

```js
new HelloWeek({
    format: 'yyyy-mm-dd',
    ....
});
```

**Solution: 2 -  Keep the format and change your array of `disableDates`:**

See this demo on [jsfiddle](https://jsfiddle.net/mauroreisvieira/3ktzLcdn/11/) with the data the you provide.

**Comment by rakshak4** [comment]
Thanks. It works now :D
